services:
  ecommerce_app:
    build: .
    image: guptaaniket05/ecommerce-fastapi:latest
    container_name: ecommerce_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"