name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - restructure-ecommerce-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-fastapi:latest .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-fastapi:latest

      # 5. Deploy on EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ecommerce

            echo "Pulling latest Docker image..."
            docker compose pull

            echo "Stopping old containers..."
            docker compose down

            echo "Starting new containers..."
            docker compose up -d

            echo "Cleaning unused images..."
            docker image prune -f

            echo "create a alembic...."
            docker exec ecommerce_app alembic upgrade head
            
            echo "Deployment successful 🚀"